### ISSUE TITLE
Setup Project Environment

### ISSUE THREAD

**Issue by vahek09** [vahek09/Domain-Implementation#1]
### Subtasks
- [ ] Initialize project repository.
- [ ] Add README file
- [ ] Add Maven Wrapper as a build tool
- [ ] Add all static analysis tools (PMD, SpotBugs, Checkstyle).
