### ISSUE TITLE
Add Databases for Weather and User datas

### ISSUE THREAD

**Issue by vahek09** [vahek09/Domain-Implementation#13]
**Description:**
Add Databases for the program

### Subtasks
- [x] Implement `WeatherData`  class.
- [x] Implement `UserData `class.
- [x]  Implement `APIKeyRepository `class.
